/**
 * Module: alert-routing-flow
 * Purpose: VS8_ROUT workflows ??Alert routing workflow [D21-5 D27-A]
 * Responsibilities: Route semantic-graph alerts (staleness warnings, invariant
 *   violations, causality anomalies) through the policy-mapper dispatch layer
 *   without hard-coded business ID routing
 * Constraints: deterministic logic, ZERO infrastructure imports, no ID hard-coding
 *
 * semantic-graph.slice/centralized-workflows/workflows/alert-routing-flow [D21-5 D27-A]
 *
 * Orchestrates the **?郎頝舐瘚?** (alert routing flow):
 *   Graph anomaly detected ??semantic alert classification ??policy resolution
 *   ??dispatch command for consumer handling.
 *
 * Alert kinds handled:
 *   - STALE_TAG      [S4]   ??tag lifecycle exceeded staleness threshold
 *   - INVARIANT_FAIL [D21-H] ??BBB/InvariantGuard rejection surfaced as alert
 *   - CAUSALITY_WARN [D21-6] ??causality tracer detected anomaly
 *
 * [D21-5] ??VS8_ROUT routing layer ??semantic reflection arc.
 * [D27-A] ??All dispatch must go through policy-mapper; no ID hard-coding.
 *
 * Dependency rule: imports from policy-mapper and dispatch-bridge ONLY.
 * ZERO infrastructure imports (no Firebase, no React, no I/O).
 */

import type { TagSlugRef } from '../core/types';
import { dispatchForTag } from '../routing/dispatch-bridge';
import type { DispatchCommand } from '../routing/dispatch-bridge';
import { resolveDispatchPolicy } from '../routing/policy-mapper';

// ??? Types ????????????????????????????????????????????????????????????????????

/** Classification of a semantic graph alert. */
export type AlertKind = 'STALE_TAG' | 'INVARIANT_FAIL' | 'CAUSALITY_WARN';

/** An alert generated by the semantic graph. */
export interface SemanticGraphAlert {
  /** Unique alert identifier. */
  readonly alertId: string;
  /** Classification of the alert. */
  readonly kind: AlertKind;
  /** The semantic tag slug involved (if applicable). */
  readonly tagSlug?: TagSlugRef;
  /** Human-readable alert message. */
  readonly message: string;
  /** ISO-8601 timestamp when the alert was generated. */
  readonly detectedAt: string;
  /** Severity: 0 (info) ??100 (critical). */
  readonly severity: number;
}

/** Result of routing an alert through the dispatch layer. */
export interface AlertRoutingResult {
  readonly alert: SemanticGraphAlert;
  /** Dispatch command produced, if a policy matched. */
  readonly dispatchCommand: DispatchCommand | null;
  /** Whether a dispatch policy was found for this alert. */
  readonly policyFound: boolean;
  /** Reason dispatch was skipped (if policyFound is false). */
  readonly skipReason?: string;
}

// ??? Alert counter ????????????????????????????????????????????????????????????

let _alertCounter = 0;

export function _resetAlertCounterForTest(): void {
  _alertCounter = 0;
}

// ??? Helpers ?????????????????????????????????????????????????????????????????

function _generateAlertId(kind: AlertKind): string {
  _alertCounter += 1;
  return `alert:${kind.toLowerCase()}:${_alertCounter}`;
}

// ??? Public API ???????????????????????????????????????????????????????????????

/**
 * Route a pre-built `SemanticGraphAlert` through the policy-mapper dispatch layer.
 *
 * If the alert carries a `tagSlug`, the policy-mapper is consulted.
 * If no policy is found, `policyFound` is `false` and `dispatchCommand` is `null`.
 *
 * [D21-5] VS8_ROUT routing arc.
 * [D27-A] ??dispatch goes through policy-mapper; no ID hard-coding.
 */
export function routeAlert(alert: SemanticGraphAlert): AlertRoutingResult {
  if (!alert.tagSlug) {
    return { alert, dispatchCommand: null, policyFound: false, skipReason: 'No tagSlug on alert.' };
  }

  const resolution = resolveDispatchPolicy(alert.tagSlug);
  if (!resolution.found) {
    return { alert, dispatchCommand: null, policyFound: false, skipReason: resolution.reason };
  }

  const dispatchResult = dispatchForTag(alert.tagSlug);
  return {
    alert,
    dispatchCommand: dispatchResult.success ? dispatchResult.command : null,
    policyFound: true,
  };
}

/**
 * Create and route a stale-tag alert [S4].
 */
export function routeStaleTagAlert(
  tagSlug: TagSlugRef,
  staleAgeMs: number
): AlertRoutingResult {
  const alert: SemanticGraphAlert = {
    alertId: _generateAlertId('STALE_TAG'),
    kind: 'STALE_TAG',
    tagSlug,
    message: `Tag "${tagSlug as string}" has been stale for ${Math.floor(staleAgeMs / 86_400_000)} days.`,
    detectedAt: new Date().toISOString(),
    severity: Math.min(100, Math.floor(staleAgeMs / 86_400_000)),
  };
  return routeAlert(alert);
}

/**
 * Create and route an invariant-failure alert [D21-H].
 */
export function routeInvariantFailAlert(
  tagSlug: TagSlugRef | undefined,
  rejectionReason: string
): AlertRoutingResult {
  const alert: SemanticGraphAlert = {
    alertId: _generateAlertId('INVARIANT_FAIL'),
    kind: 'INVARIANT_FAIL',
    tagSlug,
    message: `InvariantGuard BBB rejection: ${rejectionReason}`,
    detectedAt: new Date().toISOString(),
    severity: 90,
  };
  return routeAlert(alert);
}

/**
 * Create and route a causality warning alert [D21-6].
 */
export function routeCausalityWarnAlert(
  tagSlug: TagSlugRef,
  warningMessage: string
): AlertRoutingResult {
  const alert: SemanticGraphAlert = {
    alertId: _generateAlertId('CAUSALITY_WARN'),
    kind: 'CAUSALITY_WARN',
    tagSlug,
    message: warningMessage,
    detectedAt: new Date().toISOString(),
    severity: 50,
  };
  return routeAlert(alert);
}

