"""
✨ `File_KeyOutput` returns the primary key fields of table type `File`.

It has the same format as `File_Key`, but is only used as mutation return value.
"""
scalar File_KeyOutput
"""
✨ `Issue_KeyOutput` returns the primary key fields of table type `Issue`.

It has the same format as `Issue_Key`, but is only used as mutation return value.
"""
scalar Issue_KeyOutput
"""
✨ `Membership_KeyOutput` returns the primary key fields of table type `Membership`.

It has the same format as `Membership_Key`, but is only used as mutation return value.
"""
scalar Membership_KeyOutput
"""
✨ `Organization_KeyOutput` returns the primary key fields of table type `Organization`.

It has the same format as `Organization_Key`, but is only used as mutation return value.
"""
scalar Organization_KeyOutput
"""
✨ `Role_KeyOutput` returns the primary key fields of table type `Role`.

It has the same format as `Role_Key`, but is only used as mutation return value.
"""
scalar Role_KeyOutput
"""
✨ `Task_KeyOutput` returns the primary key fields of table type `Task`.

It has the same format as `Task_Key`, but is only used as mutation return value.
"""
scalar Task_KeyOutput
"""
✨ `User_KeyOutput` returns the primary key fields of table type `User`.

It has the same format as `User_Key`, but is only used as mutation return value.
"""
scalar User_KeyOutput
"""
✨ `Workspace_KeyOutput` returns the primary key fields of table type `Workspace`.

It has the same format as `Workspace_Key`, but is only used as mutation return value.
"""
scalar Workspace_KeyOutput
"""
✨ Generated data input type for table 'File'. It includes all necessary fields for creating or upserting rows into table.
"""
input File_Data {
  """
  ✨ Generated from Field `File`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `File`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `File`.`uploadedById` of type `UUID`
  """
  uploadedById: UUID
  """
  ✨ `_expr` server value variant of `uploadedById` (✨ Generated from Field `File`.`uploadedById` of type `UUID`)
  """
  uploadedById_expr: UUID_Expr
  """
  ✨ Generated from Field `File`.`workspaceId` of type `UUID`
  """
  workspaceId: UUID
  """
  ✨ `_expr` server value variant of `workspaceId` (✨ Generated from Field `File`.`workspaceId` of type `UUID`)
  """
  workspaceId_expr: UUID_Expr
  """
  ✨ Generated from Field `File`.`uploadedBy` of type `User`
  """
  uploadedBy: User_Key
  """
  ✨ Generated from Field `File`.`workspace` of type `Workspace`
  """
  workspace: Workspace_Key
  """
  ✨ Generated from Field `File`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `File`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `File`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `File`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `File`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `File`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `File`.`fileUrl` of type `String!`
  """
  fileUrl: String
  """
  ✨ `_expr` server value variant of `fileUrl` (✨ Generated from Field `File`.`fileUrl` of type `String!`)
  """
  fileUrl_expr: String_Expr
  """
  ✨ Generated from Field `File`.`filename` of type `String!`
  """
  filename: String
  """
  ✨ `_expr` server value variant of `filename` (✨ Generated from Field `File`.`filename` of type `String!`)
  """
  filename_expr: String_Expr
  """
  ✨ Generated from Field `File`.`version` of type `Int!`
  """
  version: Int
  """
  ✨ `_expr` server value variant of `version` (✨ Generated from Field `File`.`version` of type `Int!`)
  """
  version_expr: Int_Expr
  """
  ✨ `_update` server value variant of `version` (✨ Generated from Field `File`.`version` of type `Int!`)
  """
  version_update: [Int_Update!]
}
"""
✨ Generated filter input type for table 'File'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input File_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [File_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: File_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [File_Filter!]
  """
  ✨ Generated from Field `File`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `File`.`uploadedById` of type `UUID`
  """
  uploadedById: UUID_Filter
  """
  ✨ Generated from Field `File`.`workspaceId` of type `UUID`
  """
  workspaceId: UUID_Filter
  """
  ✨ Generated from Field `File`.`uploadedBy` of type `User`
  """
  uploadedBy: User_Filter
  """
  ✨ Generated from Field `File`.`workspace` of type `Workspace`
  """
  workspace: Workspace_Filter
  """
  ✨ Generated from Field `File`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `File`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `File`.`fileUrl` of type `String!`
  """
  fileUrl: String_Filter
  """
  ✨ Generated from Field `File`.`filename` of type `String!`
  """
  filename: String_Filter
  """
  ✨ Generated from Field `File`.`version` of type `Int!`
  """
  version: Int_Filter
}
"""
✨ Generated first-row input type for table 'File'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input File_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [File_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: File_Filter
}
"""
✨ Generated having input type for table 'File'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input File_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [File_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: File_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [File_Having!]
  """
  ✨ Generated from Field `File`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `File`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `File`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `File`.`fileUrl_count` of type `Int!`
  """
  fileUrl_count: Int_Filter
  """
  ✨ Generated from Field `File`.`filename_count` of type `Int!`
  """
  filename_count: Int_Filter
  """
  ✨ Generated from Field `File`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `File`.`uploadedById_count` of type `Int!`
  """
  uploadedById_count: Int_Filter
  """
  ✨ Generated from Field `File`.`version_count` of type `Int!`
  """
  version_count: Int_Filter
  """
  ✨ Generated from Field `File`.`workspaceId_count` of type `Int!`
  """
  workspaceId_count: Int_Filter
  """
  ✨ Generated from Field `File`.`version_sum` of type `Int`
  """
  version_sum: Int_Filter
  """
  ✨ Generated from Field `File`.`version_avg` of type `Float`
  """
  version_avg: Float_Filter
  """
  ✨ Generated from Field `File`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `File`.`version_min` of type `Int`
  """
  version_min: Int_Filter
  """
  ✨ Generated from Field `File`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `File`.`version_max` of type `Int`
  """
  version_max: Int_Filter
}
"""
✨ Generated key input type for table 'File'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input File_Key {
  """
  ✨ Generated from Field `File`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `File`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'File'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input File_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: File_Filter
}
"""
✨ Generated order input type for table 'File'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input File_Order {
  """
  ✨ Generated from Field `File`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `File`.`uploadedById` of type `UUID`
  """
  uploadedById: OrderDirection
  """
  ✨ Generated from Field `File`.`workspaceId` of type `UUID`
  """
  workspaceId: OrderDirection
  """
  ✨ Generated from Field `File`.`uploadedBy` of type `User`
  """
  uploadedBy: User_Order
  """
  ✨ Generated from Field `File`.`workspace` of type `Workspace`
  """
  workspace: Workspace_Order
  """
  ✨ Generated from Field `File`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `File`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `File`.`fileUrl` of type `String!`
  """
  fileUrl: OrderDirection
  """
  ✨ Generated from Field `File`.`filename` of type `String!`
  """
  filename: OrderDirection
  """
  ✨ Generated from Field `File`.`version` of type `Int!`
  """
  version: OrderDirection
  """
  ✨ Generated from Field `File`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `File`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `File`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `File`.`fileUrl_count` of type `Int!`
  """
  fileUrl_count: OrderDirection
  """
  ✨ Generated from Field `File`.`filename_count` of type `Int!`
  """
  filename_count: OrderDirection
  """
  ✨ Generated from Field `File`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `File`.`uploadedById_count` of type `Int!`
  """
  uploadedById_count: OrderDirection
  """
  ✨ Generated from Field `File`.`version_count` of type `Int!`
  """
  version_count: OrderDirection
  """
  ✨ Generated from Field `File`.`workspaceId_count` of type `Int!`
  """
  workspaceId_count: OrderDirection
  """
  ✨ Generated from Field `File`.`version_sum` of type `Int`
  """
  version_sum: OrderDirection
  """
  ✨ Generated from Field `File`.`version_avg` of type `Float`
  """
  version_avg: OrderDirection
  """
  ✨ Generated from Field `File`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `File`.`version_min` of type `Int`
  """
  version_min: OrderDirection
  """
  ✨ Generated from Field `File`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `File`.`version_max` of type `Int`
  """
  version_max: OrderDirection
}
"""
✨ Generated data input type for table 'Issue'. It includes all necessary fields for creating or upserting rows into table.
"""
input Issue_Data {
  """
  ✨ Generated from Field `Issue`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Issue`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Issue`.`assigneeId` of type `UUID`
  """
  assigneeId: UUID
  """
  ✨ `_expr` server value variant of `assigneeId` (✨ Generated from Field `Issue`.`assigneeId` of type `UUID`)
  """
  assigneeId_expr: UUID_Expr
  """
  ✨ Generated from Field `Issue`.`reporterId` of type `UUID`
  """
  reporterId: UUID
  """
  ✨ `_expr` server value variant of `reporterId` (✨ Generated from Field `Issue`.`reporterId` of type `UUID`)
  """
  reporterId_expr: UUID_Expr
  """
  ✨ Generated from Field `Issue`.`taskId` of type `UUID`
  """
  taskId: UUID
  """
  ✨ `_expr` server value variant of `taskId` (✨ Generated from Field `Issue`.`taskId` of type `UUID`)
  """
  taskId_expr: UUID_Expr
  """
  ✨ Generated from Field `Issue`.`workspaceId` of type `UUID`
  """
  workspaceId: UUID
  """
  ✨ `_expr` server value variant of `workspaceId` (✨ Generated from Field `Issue`.`workspaceId` of type `UUID`)
  """
  workspaceId_expr: UUID_Expr
  """
  ✨ Generated from Field `Issue`.`assignee` of type `User`
  """
  assignee: User_Key
  """
  ✨ Generated from Field `Issue`.`reporter` of type `User`
  """
  reporter: User_Key
  """
  ✨ Generated from Field `Issue`.`task` of type `Task`
  """
  task: Task_Key
  """
  ✨ Generated from Field `Issue`.`workspace` of type `Workspace`
  """
  workspace: Workspace_Key
  """
  ✨ Generated from Field `Issue`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Issue`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Issue`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Issue`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Issue`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Issue`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Issue`.`priority` of type `String!`
  """
  priority: String
  """
  ✨ `_expr` server value variant of `priority` (✨ Generated from Field `Issue`.`priority` of type `String!`)
  """
  priority_expr: String_Expr
  """
  ✨ Generated from Field `Issue`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `Issue`.`status` of type `String!`)
  """
  status_expr: String_Expr
  """
  ✨ Generated from Field `Issue`.`title` of type `String!`
  """
  title: String
  """
  ✨ `_expr` server value variant of `title` (✨ Generated from Field `Issue`.`title` of type `String!`)
  """
  title_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Issue'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Issue_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Issue_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Issue_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Issue_Filter!]
  """
  ✨ Generated from Field `Issue`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Issue`.`assigneeId` of type `UUID`
  """
  assigneeId: UUID_Filter
  """
  ✨ Generated from Field `Issue`.`reporterId` of type `UUID`
  """
  reporterId: UUID_Filter
  """
  ✨ Generated from Field `Issue`.`taskId` of type `UUID`
  """
  taskId: UUID_Filter
  """
  ✨ Generated from Field `Issue`.`workspaceId` of type `UUID`
  """
  workspaceId: UUID_Filter
  """
  ✨ Generated from Field `Issue`.`assignee` of type `User`
  """
  assignee: User_Filter
  """
  ✨ Generated from Field `Issue`.`reporter` of type `User`
  """
  reporter: User_Filter
  """
  ✨ Generated from Field `Issue`.`task` of type `Task`
  """
  task: Task_Filter
  """
  ✨ Generated from Field `Issue`.`workspace` of type `Workspace`
  """
  workspace: Workspace_Filter
  """
  ✨ Generated from Field `Issue`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Issue`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Issue`.`priority` of type `String!`
  """
  priority: String_Filter
  """
  ✨ Generated from Field `Issue`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `Issue`.`title` of type `String!`
  """
  title: String_Filter
}
"""
✨ Generated first-row input type for table 'Issue'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Issue_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Issue_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Issue_Filter
}
"""
✨ Generated having input type for table 'Issue'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Issue_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Issue_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Issue_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Issue_Having!]
  """
  ✨ Generated from Field `Issue`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`assigneeId_count` of type `Int!`
  """
  assigneeId_count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`priority_count` of type `Int!`
  """
  priority_count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`reporterId_count` of type `Int!`
  """
  reporterId_count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`taskId_count` of type `Int!`
  """
  taskId_count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`title_count` of type `Int!`
  """
  title_count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`workspaceId_count` of type `Int!`
  """
  workspaceId_count: Int_Filter
  """
  ✨ Generated from Field `Issue`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Issue`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Issue'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Issue_Key {
  """
  ✨ Generated from Field `Issue`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Issue`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Issue'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Issue_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Issue_Filter
}
"""
✨ Generated order input type for table 'Issue'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Issue_Order {
  """
  ✨ Generated from Field `Issue`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Issue`.`assigneeId` of type `UUID`
  """
  assigneeId: OrderDirection
  """
  ✨ Generated from Field `Issue`.`reporterId` of type `UUID`
  """
  reporterId: OrderDirection
  """
  ✨ Generated from Field `Issue`.`taskId` of type `UUID`
  """
  taskId: OrderDirection
  """
  ✨ Generated from Field `Issue`.`workspaceId` of type `UUID`
  """
  workspaceId: OrderDirection
  """
  ✨ Generated from Field `Issue`.`assignee` of type `User`
  """
  assignee: User_Order
  """
  ✨ Generated from Field `Issue`.`reporter` of type `User`
  """
  reporter: User_Order
  """
  ✨ Generated from Field `Issue`.`task` of type `Task`
  """
  task: Task_Order
  """
  ✨ Generated from Field `Issue`.`workspace` of type `Workspace`
  """
  workspace: Workspace_Order
  """
  ✨ Generated from Field `Issue`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Issue`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Issue`.`priority` of type `String!`
  """
  priority: OrderDirection
  """
  ✨ Generated from Field `Issue`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `Issue`.`title` of type `String!`
  """
  title: OrderDirection
  """
  ✨ Generated from Field `Issue`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`assigneeId_count` of type `Int!`
  """
  assigneeId_count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`priority_count` of type `Int!`
  """
  priority_count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`reporterId_count` of type `Int!`
  """
  reporterId_count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`taskId_count` of type `Int!`
  """
  taskId_count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`title_count` of type `Int!`
  """
  title_count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`workspaceId_count` of type `Int!`
  """
  workspaceId_count: OrderDirection
  """
  ✨ Generated from Field `Issue`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Issue`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Membership'. It includes all necessary fields for creating or upserting rows into table.
"""
input Membership_Data {
  """
  ✨ Generated from Field `Membership`.`userId` of type `UUID!`
  """
  userId: UUID
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Membership`.`userId` of type `UUID!`)
  """
  userId_expr: UUID_Expr
  """
  ✨ Generated from Field `Membership`.`organizationId` of type `UUID!`
  """
  organizationId: UUID
  """
  ✨ `_expr` server value variant of `organizationId` (✨ Generated from Field `Membership`.`organizationId` of type `UUID!`)
  """
  organizationId_expr: UUID_Expr
  """
  ✨ Generated from Field `Membership`.`organization` of type `Organization!`
  """
  organization: Organization_Key
  """
  ✨ Generated from Field `Membership`.`user` of type `User!`
  """
  user: User_Key
  """
  ✨ Generated from Field `Membership`.`roleId` of type `UUID`
  """
  roleId: UUID
  """
  ✨ `_expr` server value variant of `roleId` (✨ Generated from Field `Membership`.`roleId` of type `UUID`)
  """
  roleId_expr: UUID_Expr
  """
  ✨ Generated from Field `Membership`.`role` of type `Role`
  """
  role: Role_Key
  """
  ✨ Generated from Field `Membership`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Membership`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Membership`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Membership`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Membership`.`joinedAt` of type `Timestamp`
  """
  joinedAt: Timestamp
  """
  ✨ `_expr` server value variant of `joinedAt` (✨ Generated from Field `Membership`.`joinedAt` of type `Timestamp`)
  """
  joinedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `joinedAt` (✨ Generated from Field `Membership`.`joinedAt` of type `Timestamp`)
  """
  joinedAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `joinedAt` (✨ Generated from Field `Membership`.`joinedAt` of type `Timestamp`)
  """
  joinedAt_update: [Timestamp_Update!]
}
"""
✨ Generated filter input type for table 'Membership'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Membership_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Membership_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Membership_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Membership_Filter!]
  """
  ✨ Generated from Field `Membership`.`userId` of type `UUID!`
  """
  userId: UUID_Filter
  """
  ✨ Generated from Field `Membership`.`organizationId` of type `UUID!`
  """
  organizationId: UUID_Filter
  """
  ✨ Generated from Field `Membership`.`organization` of type `Organization!`
  """
  organization: Organization_Filter
  """
  ✨ Generated from Field `Membership`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Membership`.`roleId` of type `UUID`
  """
  roleId: UUID_Filter
  """
  ✨ Generated from Field `Membership`.`role` of type `Role`
  """
  role: Role_Filter
  """
  ✨ Generated from Field `Membership`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Membership`.`joinedAt` of type `Timestamp`
  """
  joinedAt: Timestamp_Filter
}
"""
✨ Generated first-row input type for table 'Membership'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Membership_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Membership_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Membership_Filter
}
"""
✨ Generated having input type for table 'Membership'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Membership_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Membership_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Membership_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Membership_Having!]
  """
  ✨ Generated from Field `Membership`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Membership`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Membership`.`joinedAt_count` of type `Int!`
  """
  joinedAt_count: Int_Filter
  """
  ✨ Generated from Field `Membership`.`organizationId_count` of type `Int!`
  """
  organizationId_count: Int_Filter
  """
  ✨ Generated from Field `Membership`.`roleId_count` of type `Int!`
  """
  roleId_count: Int_Filter
  """
  ✨ Generated from Field `Membership`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `Membership`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Membership`.`joinedAt_min` of type `Timestamp`
  """
  joinedAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Membership`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Membership`.`joinedAt_max` of type `Timestamp`
  """
  joinedAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Membership'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Membership_Key {
  """
  ✨ Generated from Field `Membership`.`userId` of type `UUID!`
  """
  userId: UUID
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Membership`.`userId` of type `UUID!`)
  """
  userId_expr: UUID_Expr
  """
  ✨ Generated from Field `Membership`.`organizationId` of type `UUID!`
  """
  organizationId: UUID
  """
  ✨ `_expr` server value variant of `organizationId` (✨ Generated from Field `Membership`.`organizationId` of type `UUID!`)
  """
  organizationId_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Membership'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Membership_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Membership_Filter
}
"""
✨ Generated order input type for table 'Membership'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Membership_Order {
  """
  ✨ Generated from Field `Membership`.`userId` of type `UUID!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Membership`.`organizationId` of type `UUID!`
  """
  organizationId: OrderDirection
  """
  ✨ Generated from Field `Membership`.`organization` of type `Organization!`
  """
  organization: Organization_Order
  """
  ✨ Generated from Field `Membership`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `Membership`.`roleId` of type `UUID`
  """
  roleId: OrderDirection
  """
  ✨ Generated from Field `Membership`.`role` of type `Role`
  """
  role: Role_Order
  """
  ✨ Generated from Field `Membership`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Membership`.`joinedAt` of type `Timestamp`
  """
  joinedAt: OrderDirection
  """
  ✨ Generated from Field `Membership`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Membership`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Membership`.`joinedAt_count` of type `Int!`
  """
  joinedAt_count: OrderDirection
  """
  ✨ Generated from Field `Membership`.`organizationId_count` of type `Int!`
  """
  organizationId_count: OrderDirection
  """
  ✨ Generated from Field `Membership`.`roleId_count` of type `Int!`
  """
  roleId_count: OrderDirection
  """
  ✨ Generated from Field `Membership`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `Membership`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Membership`.`joinedAt_min` of type `Timestamp`
  """
  joinedAt_min: OrderDirection
  """
  ✨ Generated from Field `Membership`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Membership`.`joinedAt_max` of type `Timestamp`
  """
  joinedAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Organization'. It includes all necessary fields for creating or upserting rows into table.
"""
input Organization_Data {
  """
  ✨ Generated from Field `Organization`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Organization`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Organization`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Organization`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Organization`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Organization`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Organization`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Organization`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Organization`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Organization`.`name` of type `String!`)
  """
  name_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Organization'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Organization_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Organization_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Organization_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Organization_Filter!]
  """
  ✨ Generated from Field `Organization`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Organization`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Organization`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Organization`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Organization`.`memberships_on_organization` of type `[Membership!]!`
  """
  memberships_on_organization: Membership_ListFilter
  """
  ✨ Generated from Field `Organization`.`workspaces_on_organization` of type `[Workspace!]!`
  """
  workspaces_on_organization: Workspace_ListFilter
  """
  ✨ Generated from Field `Organization`.`users_via_Membership` of type `[User!]!`
  """
  users_via_Membership: User_ListFilter
}
"""
✨ Generated first-row input type for table 'Organization'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Organization_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Organization_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Organization_Filter
}
"""
✨ Generated having input type for table 'Organization'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Organization_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Organization_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Organization_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Organization_Having!]
  """
  ✨ Generated from Field `Organization`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Organization`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Organization`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Organization`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Organization`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Organization`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Organization`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Organization'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Organization_Key {
  """
  ✨ Generated from Field `Organization`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Organization`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Organization'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Organization_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Organization_Filter
}
"""
✨ Generated order input type for table 'Organization'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Organization_Order {
  """
  ✨ Generated from Field `Organization`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Organization`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Organization`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Organization`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Organization`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Organization`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Organization`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Organization`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Organization`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Organization`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Organization`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Role'. It includes all necessary fields for creating or upserting rows into table.
"""
input Role_Data {
  """
  ✨ Generated from Field `Role`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Role`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Role`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Role`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Role`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Role`.`name` of type `String!`)
  """
  name_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Role'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Role_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Role_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Role_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Role_Filter!]
  """
  ✨ Generated from Field `Role`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Role`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Role`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Role`.`memberships_on_role` of type `[Membership!]!`
  """
  memberships_on_role: Membership_ListFilter
}
"""
✨ Generated first-row input type for table 'Role'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Role_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Role_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Role_Filter
}
"""
✨ Generated having input type for table 'Role'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Role_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Role_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Role_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Role_Having!]
  """
  ✨ Generated from Field `Role`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Role`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Role`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Role`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
}
"""
✨ Generated key input type for table 'Role'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Role_Key {
  """
  ✨ Generated from Field `Role`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Role`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Role'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Role_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Role_Filter
}
"""
✨ Generated order input type for table 'Role'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Role_Order {
  """
  ✨ Generated from Field `Role`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Role`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Role`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Role`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Role`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Role`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Role`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
}
"""
✨ Generated data input type for table 'Task'. It includes all necessary fields for creating or upserting rows into table.
"""
input Task_Data {
  """
  ✨ Generated from Field `Task`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Task`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Task`.`assignedToId` of type `UUID`
  """
  assignedToId: UUID
  """
  ✨ `_expr` server value variant of `assignedToId` (✨ Generated from Field `Task`.`assignedToId` of type `UUID`)
  """
  assignedToId_expr: UUID_Expr
  """
  ✨ Generated from Field `Task`.`parentId` of type `UUID`
  """
  parentId: UUID
  """
  ✨ `_expr` server value variant of `parentId` (✨ Generated from Field `Task`.`parentId` of type `UUID`)
  """
  parentId_expr: UUID_Expr
  """
  ✨ Generated from Field `Task`.`workspaceId` of type `UUID`
  """
  workspaceId: UUID
  """
  ✨ `_expr` server value variant of `workspaceId` (✨ Generated from Field `Task`.`workspaceId` of type `UUID`)
  """
  workspaceId_expr: UUID_Expr
  """
  ✨ Generated from Field `Task`.`assignedTo` of type `User`
  """
  assignedTo: User_Key
  """
  ✨ Generated from Field `Task`.`parent` of type `Task`
  """
  parent: Task_Key
  """
  ✨ Generated from Field `Task`.`workspace` of type `Workspace`
  """
  workspace: Workspace_Key
  """
  ✨ Generated from Field `Task`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Task`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Task`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Task`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Task`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Task`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Task`.`dueDate` of type `Timestamp`
  """
  dueDate: Timestamp
  """
  ✨ `_expr` server value variant of `dueDate` (✨ Generated from Field `Task`.`dueDate` of type `Timestamp`)
  """
  dueDate_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `dueDate` (✨ Generated from Field `Task`.`dueDate` of type `Timestamp`)
  """
  dueDate_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `dueDate` (✨ Generated from Field `Task`.`dueDate` of type `Timestamp`)
  """
  dueDate_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Task`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `Task`.`status` of type `String!`)
  """
  status_expr: String_Expr
  """
  ✨ Generated from Field `Task`.`title` of type `String!`
  """
  title: String
  """
  ✨ `_expr` server value variant of `title` (✨ Generated from Field `Task`.`title` of type `String!`)
  """
  title_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Task'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Task_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Task_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Task_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Task_Filter!]
  """
  ✨ Generated from Field `Task`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Task`.`assignedToId` of type `UUID`
  """
  assignedToId: UUID_Filter
  """
  ✨ Generated from Field `Task`.`parentId` of type `UUID`
  """
  parentId: UUID_Filter
  """
  ✨ Generated from Field `Task`.`workspaceId` of type `UUID`
  """
  workspaceId: UUID_Filter
  """
  ✨ Generated from Field `Task`.`assignedTo` of type `User`
  """
  assignedTo: User_Filter
  """
  ✨ Generated from Field `Task`.`parent` of type `Task`
  """
  parent: Task_Filter
  """
  ✨ Generated from Field `Task`.`workspace` of type `Workspace`
  """
  workspace: Workspace_Filter
  """
  ✨ Generated from Field `Task`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Task`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Task`.`dueDate` of type `Timestamp`
  """
  dueDate: Timestamp_Filter
  """
  ✨ Generated from Field `Task`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `Task`.`title` of type `String!`
  """
  title: String_Filter
  """
  ✨ Generated from Field `Task`.`issues_on_task` of type `[Issue!]!`
  """
  issues_on_task: Issue_ListFilter
  """
  ✨ Generated from Field `Task`.`tasks_on_parent` of type `[Task!]!`
  """
  tasks_on_parent: Task_ListFilter
}
"""
✨ Generated first-row input type for table 'Task'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Task_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Task_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Task_Filter
}
"""
✨ Generated having input type for table 'Task'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Task_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Task_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Task_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Task_Having!]
  """
  ✨ Generated from Field `Task`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Task`.`assignedToId_count` of type `Int!`
  """
  assignedToId_count: Int_Filter
  """
  ✨ Generated from Field `Task`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Task`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Task`.`dueDate_count` of type `Int!`
  """
  dueDate_count: Int_Filter
  """
  ✨ Generated from Field `Task`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Task`.`parentId_count` of type `Int!`
  """
  parentId_count: Int_Filter
  """
  ✨ Generated from Field `Task`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `Task`.`title_count` of type `Int!`
  """
  title_count: Int_Filter
  """
  ✨ Generated from Field `Task`.`workspaceId_count` of type `Int!`
  """
  workspaceId_count: Int_Filter
  """
  ✨ Generated from Field `Task`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Task`.`dueDate_min` of type `Timestamp`
  """
  dueDate_min: Timestamp_Filter
  """
  ✨ Generated from Field `Task`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Task`.`dueDate_max` of type `Timestamp`
  """
  dueDate_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Task'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Task_Key {
  """
  ✨ Generated from Field `Task`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Task`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Task'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Task_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Task_Filter
}
"""
✨ Generated order input type for table 'Task'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Task_Order {
  """
  ✨ Generated from Field `Task`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Task`.`assignedToId` of type `UUID`
  """
  assignedToId: OrderDirection
  """
  ✨ Generated from Field `Task`.`parentId` of type `UUID`
  """
  parentId: OrderDirection
  """
  ✨ Generated from Field `Task`.`workspaceId` of type `UUID`
  """
  workspaceId: OrderDirection
  """
  ✨ Generated from Field `Task`.`assignedTo` of type `User`
  """
  assignedTo: User_Order
  """
  ✨ Generated from Field `Task`.`parent` of type `Task`
  """
  parent: Task_Order
  """
  ✨ Generated from Field `Task`.`workspace` of type `Workspace`
  """
  workspace: Workspace_Order
  """
  ✨ Generated from Field `Task`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Task`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Task`.`dueDate` of type `Timestamp`
  """
  dueDate: OrderDirection
  """
  ✨ Generated from Field `Task`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `Task`.`title` of type `String!`
  """
  title: OrderDirection
  """
  ✨ Generated from Field `Task`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Task`.`assignedToId_count` of type `Int!`
  """
  assignedToId_count: OrderDirection
  """
  ✨ Generated from Field `Task`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Task`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Task`.`dueDate_count` of type `Int!`
  """
  dueDate_count: OrderDirection
  """
  ✨ Generated from Field `Task`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Task`.`parentId_count` of type `Int!`
  """
  parentId_count: OrderDirection
  """
  ✨ Generated from Field `Task`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `Task`.`title_count` of type `Int!`
  """
  title_count: OrderDirection
  """
  ✨ Generated from Field `Task`.`workspaceId_count` of type `Int!`
  """
  workspaceId_count: OrderDirection
  """
  ✨ Generated from Field `Task`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Task`.`dueDate_min` of type `Timestamp`
  """
  dueDate_min: OrderDirection
  """
  ✨ Generated from Field `Task`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Task`.`dueDate_max` of type `Timestamp`
  """
  dueDate_max: OrderDirection
}
"""
✨ Generated data input type for table 'User'. It includes all necessary fields for creating or upserting rows into table.
"""
input User_Data {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: String
  """
  ✨ `_expr` server value variant of `displayName` (✨ Generated from Field `User`.`displayName` of type `String!`)
  """
  displayName_expr: String_Expr
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `User`.`email` of type `String!`)
  """
  email_expr: String_Expr
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String
  """
  ✨ `_expr` server value variant of `photoUrl` (✨ Generated from Field `User`.`photoUrl` of type `String`)
  """
  photoUrl_expr: String_Expr
}
"""
✨ Generated filter input type for table 'User'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [User_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: User_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [User_Filter!]
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: String_Filter
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String_Filter
  """
  ✨ Generated from Field `User`.`files_on_uploadedBy` of type `[File!]!`
  """
  files_on_uploadedBy: File_ListFilter
  """
  ✨ Generated from Field `User`.`issues_on_assignee` of type `[Issue!]!`
  """
  issues_on_assignee: Issue_ListFilter
  """
  ✨ Generated from Field `User`.`issues_on_reporter` of type `[Issue!]!`
  """
  issues_on_reporter: Issue_ListFilter
  """
  ✨ Generated from Field `User`.`memberships_on_user` of type `[Membership!]!`
  """
  memberships_on_user: Membership_ListFilter
  """
  ✨ Generated from Field `User`.`tasks_on_assignedTo` of type `[Task!]!`
  """
  tasks_on_assignedTo: Task_ListFilter
  """
  ✨ Generated from Field `User`.`workspaces_on_user` of type `[Workspace!]!`
  """
  workspaces_on_user: Workspace_ListFilter
  """
  ✨ Generated from Field `User`.`organizations_via_Membership` of type `[Organization!]!`
  """
  organizations_via_Membership: Organization_ListFilter
}
"""
✨ Generated first-row input type for table 'User'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input User_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [User_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: User_Filter
}
"""
✨ Generated having input type for table 'User'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [User_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: User_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [User_Having!]
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: Int_Filter
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `User`.`photoUrl_count` of type `Int!`
  """
  photoUrl_count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'User'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input User_Key {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'User'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input User_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: User_Filter
}
"""
✨ Generated order input type for table 'User'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input User_Order {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: OrderDirection
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: OrderDirection
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: OrderDirection
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl_count` of type `Int!`
  """
  photoUrl_count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Workspace'. It includes all necessary fields for creating or upserting rows into table.
"""
input Workspace_Data {
  """
  ✨ Generated from Field `Workspace`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Workspace`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Workspace`.`organizationId` of type `UUID`
  """
  organizationId: UUID
  """
  ✨ `_expr` server value variant of `organizationId` (✨ Generated from Field `Workspace`.`organizationId` of type `UUID`)
  """
  organizationId_expr: UUID_Expr
  """
  ✨ Generated from Field `Workspace`.`userId` of type `UUID`
  """
  userId: UUID
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Workspace`.`userId` of type `UUID`)
  """
  userId_expr: UUID_Expr
  """
  ✨ Generated from Field `Workspace`.`organization` of type `Organization`
  """
  organization: Organization_Key
  """
  ✨ Generated from Field `Workspace`.`user` of type `User`
  """
  user: User_Key
  """
  ✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Workspace`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Workspace`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Workspace`.`isPersonal` of type `Boolean!`
  """
  isPersonal: Boolean
  """
  ✨ `_expr` server value variant of `isPersonal` (✨ Generated from Field `Workspace`.`isPersonal` of type `Boolean!`)
  """
  isPersonal_expr: Boolean_Expr
  """
  ✨ Generated from Field `Workspace`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Workspace`.`name` of type `String!`)
  """
  name_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Workspace'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Workspace_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Workspace_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Workspace_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Workspace_Filter!]
  """
  ✨ Generated from Field `Workspace`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Workspace`.`organizationId` of type `UUID`
  """
  organizationId: UUID_Filter
  """
  ✨ Generated from Field `Workspace`.`userId` of type `UUID`
  """
  userId: UUID_Filter
  """
  ✨ Generated from Field `Workspace`.`organization` of type `Organization`
  """
  organization: Organization_Filter
  """
  ✨ Generated from Field `Workspace`.`user` of type `User`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Workspace`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Workspace`.`isPersonal` of type `Boolean!`
  """
  isPersonal: Boolean_Filter
  """
  ✨ Generated from Field `Workspace`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Workspace`.`files_on_workspace` of type `[File!]!`
  """
  files_on_workspace: File_ListFilter
  """
  ✨ Generated from Field `Workspace`.`issues_on_workspace` of type `[Issue!]!`
  """
  issues_on_workspace: Issue_ListFilter
  """
  ✨ Generated from Field `Workspace`.`tasks_on_workspace` of type `[Task!]!`
  """
  tasks_on_workspace: Task_ListFilter
}
"""
✨ Generated first-row input type for table 'Workspace'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Workspace_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Workspace_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Workspace_Filter
}
"""
✨ Generated having input type for table 'Workspace'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Workspace_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Workspace_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Workspace_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Workspace_Having!]
  """
  ✨ Generated from Field `Workspace`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Workspace`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Workspace`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Workspace`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Workspace`.`isPersonal_count` of type `Int!`
  """
  isPersonal_count: Int_Filter
  """
  ✨ Generated from Field `Workspace`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Workspace`.`organizationId_count` of type `Int!`
  """
  organizationId_count: Int_Filter
  """
  ✨ Generated from Field `Workspace`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `Workspace`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Workspace`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Workspace'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Workspace_Key {
  """
  ✨ Generated from Field `Workspace`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Workspace`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Workspace'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Workspace_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Workspace_Filter
}
"""
✨ Generated order input type for table 'Workspace'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Workspace_Order {
  """
  ✨ Generated from Field `Workspace`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`organizationId` of type `UUID`
  """
  organizationId: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`userId` of type `UUID`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`organization` of type `Organization`
  """
  organization: Organization_Order
  """
  ✨ Generated from Field `Workspace`.`user` of type `User`
  """
  user: User_Order
  """
  ✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`isPersonal` of type `Boolean!`
  """
  isPersonal: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`isPersonal_count` of type `Int!`
  """
  isPersonal_count: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`organizationId_count` of type `Int!`
  """
  organizationId_count: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
