// Thin re-export stub — workspace domain types have moved to @/features/workspace.slice.
// This file is kept for backward compatibility with existing @/shared/types imports.
export type {
  WorkspaceRole,
  WorkspaceLifecycleState,
  WorkspacePersonnel,
  Workspace,
  WorkspaceGrant,
  CapabilitySpec,
  Capability,
  Address,
  WorkspaceLocation,
  Location,
  WorkspaceTask,
  IssueComment,
  WorkspaceIssue,
  WorkspaceFileVersion,
  WorkspaceFile,
  IntentID,
  SourcePointer,
  ParsedLineItem,
  ParsingIntentSourceType,
  ParsingIntentReviewStatus,
  ParsingIntent,
  ParsingImportStatus,
  ParsingImport,
} from '@/features/workspace.slice'
